/**
 * Smart Agriculture Platform (SAP) — Local Agronomic Knowledge Base
 * 100% On-Device / Offline Disease & Crop Intelligence (No Cloud API)
 */

const AGRONOMIC_KNOWLEDGE = {
  "Wheat___Yellow_rust": {
    "crop": "Wheat",
    "disease_name_en": "Wheat Stripe / Yellow Rust (Puccinia striiformis)",
    "disease_name_hi": "गेहूं का पीला रतुआ (येलो रस्ट)",
    "is_healthy": false,
    "symptoms_en": "Linear yellow-orange stripes of urediniospore pustules develop parallel to leaf veins. Pustules rupture the epidermis, causing rapid leaf drying.",
    "symptoms_hi": "पत्तियों की नसों के समानांतर चमकीली पीली-नारंगी धारियां और पाउडर जैसी फुंसियां। पत्तियों का तेजी से सूखना।",
    "organic_remedy_en": "Spray Neem seed kernel extract (NSKE 5%) or Trichoderma harzianum (5g/L). Dust sulfur (25 kg/ha) in early stage.",
    "organic_remedy_hi": "नीम बीज का अर्क (NSKE 5%) या ट्राइकोडर्मा हरजियनम (5 ग्राम/लीटर) का छिड़काव करें। शुरुआती अवस्था में सल्फर का भुरकाव करें।",
    "chemical_treatment_en": "Propiconazole 25% EC (Tilt) @ 1 ml/L or Tebuconazole 25.9% EC @ 1.25 ml/L at first appearance of yellow pustules.",
    "chemical_treatment_hi": "प्रोपिकोनाज़ोल 25% EC (टिल्ट) 1 मिली/लीटर अथवा टेबुकोनाज़ोल 1.25 मिली/लीटर पानी में मिलाकर स्प्रे करें।",
    "prevention_en": "Sow rust-resistant wheat varieties (HD-3086, DBW-187, DBW-222). Avoid excess nitrogen; avoid late sowing.",
    "prevention_hi": "प्रतिरोधी किस्में (HD-3086, DBW-187) बोएं। अत्यधिक यूरिया से बचें और समय पर बुवाई करें।"
  },
  "Wheat___healthy": {
    "crop": "Wheat",
    "disease_name_en": "Healthy Wheat Crop",
    "disease_name_hi": "स्वस्थ गेहूं की फसल",
    "is_healthy": true,
    "symptoms_en": "Lush green foliage with uniform chlorophyll pigmentation, clean turgid leaves, and no pathogenic lesions.",
    "symptoms_hi": "पत्तियां पूरी तरह स्वस्थ, हरी-भरी और किसी भी प्रकार के रोग धब्बों से मुक्त हैं।",
    "organic_remedy_en": "Maintain soil organic matter with compost or vermicompost. Spray Panchagavya 3% as a plant growth tonic.",
    "organic_remedy_hi": "गोबर की खाद या वर्मीकम्पोस्ट डालें। वृद्धि के लिए 3% पंचगव्य का छिड़काव करें।",
    "chemical_treatment_en": "No chemical fungicide required. Maintain balanced NPK nutrition (120:60:40 kg/ha).",
    "chemical_treatment_hi": "किसी रासायनिक दवा की आवश्यकता नहीं है। संतुलित पोषक तत्व बनाए रखें।",
    "prevention_en": "Schedule regular field monitoring; ensure proper crown root initiation irrigation at 21 days.",
    "prevention_hi": "नियमित रूप से खेत की निगरानी करें और समय पर सिंचाई करें।"
  },
  "Cotton___Bacterial_blight": {
    "crop": "Cotton",
    "disease_name_en": "Cotton Bacterial Blight (Xanthomonas citri pv. malvacearum)",
    "disease_name_hi": "कपास का जीवाणु झुलसा (एंगुलर लीफ स्पॉट)",
    "is_healthy": false,
    "symptoms_en": "Angular water-soaked leaf spots bounded by small veinlets, turning reddish-brown to dark black lesions. Can cause blackarm stage on stems.",
    "symptoms_hi": "पत्तियों की नसों से घिरे कोणीय जलसिक्त धब्बे जो बाद में गहरे भूरे/काले हो जाते हैं।",
    "organic_remedy_en": "Seed bio-priming with Pseudomonas fluorescens (10g/kg seed). Spray cow dung slurry filtrate (10%) with turmeric.",
    "organic_remedy_hi": "स्यूडोमोनास फ्लोरोसेंस (10 ग्राम/किग्रा) से बीजोपचार करें। नीम के तेल का छिड़काव करें।",
    "chemical_treatment_en": "Copper Oxychloride 50% WP (2.5 g/L) mixed with Streptocycline or Plantomycin (100 mg/L) sprayed twice at 12-day interval.",
    "chemical_treatment_hi": "कॉपर ऑक्सीक्लोराइड (2.5 ग्राम/लीटर) + स्ट्रेप्टोसाइक्लिन (100 मिग्रा/लीटर) का घोल बनाकर छिड़कें।",
    "prevention_en": "Acid delinting of cotton seeds; practice crop rotation with cereals; rogue out infected plant debris.",
    "prevention_hi": "प्रमाणित बीजों का उपयोग करें, फसल चक्र अपनाएं और संक्रमित अवशेष नष्ट करें।"
  },
  "Cotton___healthy": {
    "crop": "Cotton",
    "disease_name_en": "Healthy Cotton Leaf",
    "disease_name_hi": "स्वस्थ कपास की पत्ती",
    "is_healthy": true,
    "symptoms_en": "Robust palmately lobed green leaves without angular water-soaking, necrotic veins, or curling.",
    "symptoms_hi": "पत्तियां सामान्य हरी, चमकदार और जीवाणु या कीट के प्रकोप से मुक्त हैं।",
    "organic_remedy_en": "Apply Jeevamrutha through irrigation; spray diluted cow urine (5%) as natural repellent.",
    "organic_remedy_hi": "जीवामृत का प्रयोग करें और नीम अर्क का हल्का छिड़काव रखें।",
    "chemical_treatment_en": "No chemical fungicide required. Monitor for sucking pests (whiteflies, thrips).",
    "chemical_treatment_hi": "किसी फफूंदनाशी की जरूरत नहीं। कीट निगरानी बनाए रखें।",
    "prevention_en": "Ensure adequate potassium nutrition to enhance natural plant defense mechanisms.",
    "prevention_hi": "पोटाश की उचित मात्रा दें ताकि पौधों की रोग प्रतिरोधक क्षमता मजबूत रहे।"
  },
  "Sugarcane___Red_rot": {
    "crop": "Sugarcane",
    "disease_name_en": "Sugarcane Red Rot (Colletotrichum falcatum)",
    "disease_name_hi": "गन्ने का लाल सड़न रोग (रेड रॉट)",
    "is_healthy": false,
    "symptoms_en": "Yellowing and drying of crown leaves. Characteristic red discoloration of midrib with white cross-bands; internal stalk tissues show red pith with alcohol smell.",
    "symptoms_hi": "पत्तियों की मुख्य शिरा (मिडरिब) पर लाल रंग के धब्बे और सफेद आड़ी पट्टियां। तने को चीरने पर अंदर लाल गूदा।",
    "organic_remedy_en": "Dip setts in Trichoderma viride culture (10g/L) for 30 minutes before planting. Apply bio-fertilizers.",
    "organic_remedy_hi": "बुवाई से पूर्व गूलों को ट्राइकोडर्मा विरिडी (10 ग्राम/लीटर) के घोल में 30 मिनट उपचारित करें।",
    "chemical_treatment_en": "Carbendazim 50% WP (1g/L) or Thiophanate Methyl 70% WP (1g/L) sett dip treatment. Foliar spray of Carbendazim + Mancozeb (2g/L).",
    "chemical_treatment_hi": "कार्बेन्डाजिम (1 ग्राम/लीटर) घोल में गूलों का उपचार करें। खड़ी फसल में मैंकोजेब (2 ग्राम/लीटर) स्प्रे करें।",
    "prevention_en": "Use certified disease-free setts; implement hot water sett treatment at 52°C for 30 min; avoid ratoon of infected fields.",
    "prevention_hi": "स्वस्थ बीजों का चयन करें, 52°C गर्म पानी में 30 मिनट उपचार करें, रोगग्रस्त खेत में पेड़ी न लें।"
  },
  "Sugarcane___healthy": {
    "crop": "Sugarcane",
    "disease_name_en": "Healthy Sugarcane Foliage",
    "disease_name_hi": "स्वस्थ गन्ने की पत्ती",
    "is_healthy": true,
    "symptoms_en": "Vibrant emerald green elongate leaves with clear white central midrib, free of lesions or spindle rot.",
    "symptoms_hi": "पत्तियां पूरी तरह हरी, चमकदार और मध्य शिरा साफ-सुथरी है।",
    "organic_remedy_en": "Incorporate pressmud compost or farmyard manure (FYM @ 10 t/ha).",
    "organic_remedy_hi": "प्रेसमड या सड़ी गोबर खाद डालें।",
    "chemical_treatment_en": "No chemical fungicide required. Apply nitrogen in splits to maintain vegetative vigor.",
    "chemical_treatment_hi": "किसी रासायनिक दवा की आवश्यकता नहीं।",
    "prevention_en": "Ensure proper field drainage during monsoon to prevent water stagnation.",
    "prevention_hi": "वर्षा के मौसम में जल निकासी की समुचित व्यवस्था रखें।"
  },
  "Potato___Early_blight": {
    "crop": "Potato",
    "disease_name_en": "Potato Early Blight (Alternaria solani)",
    "disease_name_hi": "आलू का अगेती झुलसा (अल्टरनेरिया सोलेनाई)",
    "is_healthy": false,
    "symptoms_en": "Dark brown to black necrotic spots with characteristic concentric rings (target board pattern) starting on older lower leaves. Surrounding tissue turns chlorotic yellow.",
    "symptoms_hi": "पत्तियों पर गहरे भूरे-काले संकेंद्री छल्ले (टारगेट बोर्ड जैसे छल्ले) बनते हैं। धब्बों के आसपास पत्ती पीली पड़ जाती है।",
    "organic_remedy_en": "Spray Trichoderma viride @ 5g/L or 5% neem seed kernel extract (NSKE). Apply copper soap spray.",
    "organic_remedy_hi": "ट्राइकोडर्मा विरिडी (5 ग्राम/लीटर) या नीम अर्क (5%) का छिड़काव करें। कॉपर सल्फेट आधारित जैव घोल उपयोगी है।",
    "chemical_treatment_en": "Mancozeb 75% WP @ 2.5 g/L or Chlorothalonil 75% WP @ 2 g/L. In severe cases, Azoxystrobin 23% SC @ 1 ml/L.",
    "chemical_treatment_hi": "मैंकोज़ेब 75% WP (2.5 ग्राम/लीटर) या क्लोरोथैलोनिल (2 ग्राम/लीटर) का 10-12 दिन के अंतराल पर छिड़काव करें।",
    "prevention_en": "Practice 3-year crop rotation with non-solanaceous crops; maintain balanced nitrogen and potassium fertilization.",
    "prevention_hi": "3 वर्षीय फसल चक्र अपनाएं, संतुलित पोटाश दें और अत्यधिक नमी से बचें।"
  },
  "Potato___Late_blight": {
    "crop": "Potato",
    "disease_name_en": "Potato Late Blight (Phytophthora infestans)",
    "disease_name_hi": "आलू का पिछेता झुलसा (लेट ब्लाइट)",
    "is_healthy": false,
    "symptoms_en": "Irregular dark water-soaked lesions on leaf margins and tips, rapidly enlarging into purplish-brown necrotic patches. White cottony fungal growth on leaf undersides in high humidity.",
    "symptoms_hi": "पत्तियों के किनारों पर जलसिक्त धब्बे जो तेजी से गहरे कत्थई/काले हो जाते हैं। नमी में पत्ती के नीचे सफेद फफूंद।",
    "organic_remedy_en": "Foliar spray with Bordeaux mixture (1%) or copper hydroxide (2.5 g/L). Apply bio-formulations of Bacillus subtilis.",
    "organic_remedy_hi": "बोर्डो मिश्रण (1%) या कॉपर हाइड्रॉक्साइड (2.5 ग्राम/लीटर) का छिड़काव करें।",
    "chemical_treatment_en": "Cymoxanil 8% + Mancozeb 64% WP (Curzate @ 2.5 g/L) or Dimethomorph 50% WP (1g/L) + Mancozeb (2g/L).",
    "chemical_treatment_hi": "साइमोक्सानिल + मैंकोजेब (2.5 ग्राम/लीटर) अथवा डाइमेशोमॉर्फ (1 ग्राम/लीटर) का तुरंत छिड़काव करें।",
    "prevention_en": "Plant certified blight-resistant tubers (Kufri Pukhraj, Kufri Jyoti); destroy volunteer potatoes; avoid sprinkler irrigation.",
    "prevention_hi": "प्रमाणित बीज लगाएं, कतारों में मिट्टी चढ़ाएं और शाम को सिंचाई से बचें।"
  },
  "Potato___healthy": {
    "crop": "Potato",
    "disease_name_en": "Healthy Potato Leaf",
    "disease_name_hi": "स्वस्थ आलू की पत्ती",
    "is_healthy": true,
    "symptoms_en": "Compound dark green foliage without necrotic margins, purplish water-soaked edges, or wilt.",
    "symptoms_hi": "आलू की पत्तियां पूरी तरह स्वस्थ, हरी और किसी भी झुलसा या मोजैक रोग से मुक्त हैं।",
    "organic_remedy_en": "Apply vermiwash spray (5%) to boost foliar micronutrient absorption.",
    "organic_remedy_hi": "पोषक तत्वों के लिए वर्मीवाश (5%) का छिड़काव करें।",
    "chemical_treatment_en": "No chemical treatment required. Preventive spray of Mancozeb 75% WP (2 g/L) before foggy weather.",
    "chemical_treatment_hi": "रोग नहीं है। कोहरे वाले मौसम से पहले बचाव हेतु केवल हल्का मैंकोजेब छिड़क सकते हैं।",
    "prevention_en": "Maintain regular ridging and earthing up to protect tubers from surface exposure.",
    "prevention_hi": "उचित मिट्टी चढ़ाएं ताकि कंद सुरक्षित रहें।"
  },
  "Rice___Blast": {
    "crop": "Rice",
    "disease_name_en": "Rice Leaf Blast (Magnaporthe oryzae / Pyricularia oryzae)",
    "disease_name_hi": "धान का झोंका / ब्लास्ट रोग",
    "is_healthy": false,
    "symptoms_en": "Spindle-shaped / diamond-shaped lesions with grayish-white centers and dark brown or reddish borders. Lesions coalesce causing total leaf death (leaf blast).",
    "symptoms_hi": "पत्तियों पर आंख या नाव के आकार के धब्बे जिनका केंद्र धूसर-सफेद और किनारे भूरे-लाल होते हैं।",
    "organic_remedy_en": "Foliar spray with Pseudomonas fluorescens (0.2%) or Kasugamycin bio-ferment. Apply fermented butter-milk (chhaas) @ 5%.",
    "organic_remedy_hi": "स्यूडोमोनास फ्लोरोसेंस (2 ग्राम/लीटर) या खट्टी छाछ (5%) का छिड़काव करें।",
    "chemical_treatment_en": "Tricyclazole 75% WP (Beam @ 0.6 g/L) or Isoprothiolane 40% EC (1.5 ml/L) or Azoxystrobin + Difenoconazole (1 ml/L).",
    "chemical_treatment_hi": "ट्राइसाइक्लाजोल 75% WP (0.6 ग्राम/लीटर) अथवा आइसोप्रोपियोलेन (1.5 मिली/लीटर) पानी में घोलकर स्प्रे करें।",
    "prevention_en": "Avoid excessive nitrogen fertilizers; maintain standing water layer in paddy fields; burn infected straw.",
    "prevention_hi": "यूरिया का अत्यधिक उपयोग न करें, खेत में जल का स्तर बनाए रखें और रोगग्रस्त पुआल नष्ट करें।"
  },
  "Rice___Brown_spot": {
    "crop": "Rice",
    "disease_name_en": "Rice Brown Spot (Bipolaris oryzae / Helminthosporium oryzae)",
    "disease_name_hi": "धान का भूरा धब्बा रोग (ब्राउन स्पॉट)",
    "is_healthy": false,
    "symptoms_en": "Small circular to oval brown spots with dark reddish-brown margins and grey or yellowish centers across leaf blades and glumes.",
    "symptoms_hi": "पत्तियों और दानों पर गोल अथवा अंडाकार भूरे धब्बे, जिनके केंद्र में धूसर व किनारों पर गहरा लाल-भूरा घेरा होता है।",
    "organic_remedy_en": "Seed treatment with Pseudomonas fluorescens @ 10g/kg. Foliar spray of fermented cow urine with neem extract.",
    "organic_remedy_hi": "स्यूडोमोनास फ्लोरोसेंस (10 ग्राम/किग्रा) से बीजोपचार करें। नीम अर्क युक्त जीवामृत का छिड़काव करें।",
    "chemical_treatment_en": "Propiconazole 25% EC @ 1 ml/L or Mancozeb 75% WP @ 2 g/L or Edifenphos 50% EC @ 1 ml/L.",
    "chemical_treatment_hi": "प्रोपिकोनाज़ोल 25% EC (1 मिली/लीटर) या मैंकोज़ेब (2 ग्राम/लीटर) का छिड़काव करें।",
    "prevention_en": "Soil testing to correct nutrient deficiencies (especially potassium, zinc, and silicon); avoid drought stress.",
    "prevention_hi": "पोटाश व जिंक की कमी दूर करें; खेत में पर्याप्त नमी बनाए रखें।"
  },
  "Rice___healthy": {
    "crop": "Rice",
    "disease_name_en": "Healthy Rice Leaf",
    "disease_name_hi": "स्वस्थ धान की पत्ती",
    "is_healthy": true,
    "symptoms_en": "Uniform linear emerald green blade with sharp apex, free from spindle lesions or sheath rot.",
    "symptoms_hi": "पत्तियां पूरी तरह स्वस्थ, हरी और किसी भी धब्बे या झुलसा से रहित हैं।",
    "organic_remedy_en": "Apply Azospirillum and Phosphobacteria bio-fertilizers in root zone.",
    "organic_remedy_hi": "जड़ों में जैव उर्वरक (एज़ोस्पिरिलम) का प्रयोग करें।",
    "chemical_treatment_en": "No chemical fungicide required. Maintain balanced nitrogen-potash split application.",
    "chemical_treatment_hi": "किसी रासायनिक फफूंदनाशी की आवश्यकता नहीं।",
    "prevention_en": "Regularly scout borders; drain and re-flood fields periodically to aerate root system.",
    "prevention_hi": "खेत की नियमित जांच रखें और समय-समय पर पानी बदलते रहें।"
  },
  "Soybean___Rust": {
    "crop": "Soybean",
    "disease_name_en": "Soybean Rust (Phakopsora pachyrhizi)",
    "disease_name_hi": "सोयाबीन का गेरूई / रस्ट रोग",
    "is_healthy": false,
    "symptoms_en": "Tiny chlorotic pinhead spots on upper leaf surface corresponding to raised brown/tan uredinia pustules on the lower leaf surface, leading to rapid defoliation.",
    "symptoms_hi": "पत्ती की निचली सतह पर छोटे भूरे-भूरे उभरे हुए फफोले (पस्ट्यूल्स) और समय से पहले पत्तों का झड़ना।",
    "organic_remedy_en": "Foliar spray with garlic bulb extract (5%) or Neem formulation (3000 ppm @ 3 ml/L).",
    "organic_remedy_hi": "लहसुन का अर्क (5%) या नीम का तेल (3 मिली/लीटर) का छिड़काव करें।",
    "chemical_treatment_en": "Hexaconazole 5% EC (2 ml/L) or Tebuconazole 25.9% EC (1.5 ml/L) or Propiconazole 25% EC (1 ml/L) at first sign.",
    "chemical_treatment_hi": "हेक्साकोनाज़ोल 5% EC (2 मिली/लीटर) या टेबुकोनाज़ोल (1.5 मिली/लीटर) का तुरंत छिड़काव करें।",
    "prevention_en": "Early sowing; wider row spacing (45 cm) for canopy aeration; rogue alternate legume hosts.",
    "prevention_hi": "उचित दूरी (45 सेमी) पर बुवाई करें ताकि हवा का आवागमन बना रहे।"
  },
  "Soybean___healthy": {
    "crop": "Soybean",
    "disease_name_en": "Healthy Soybean Leaf",
    "disease_name_hi": "स्वस्थ सोयाबीन की पत्ती",
    "is_healthy": true,
    "symptoms_en": "Trifoliate rich green leaves with intact lamina and veins, showing no pustules or mosaic mottling.",
    "symptoms_hi": "सोयाबीन की पत्तियां पूरी तरह स्वस्थ, हरी और रोगमुक्त हैं।",
    "organic_remedy_en": "Inoculate seeds with Rhizobium japonicum before sowing for nitrogen fixation.",
    "organic_remedy_hi": "राइजोबियम कल्चर से बीजोपचार करें।",
    "chemical_treatment_en": "No chemical fungicide required.",
    "chemical_treatment_hi": "किसी रासायनिक दवा की आवश्यकता नहीं।",
    "prevention_en": "Maintain weed-free conditions during initial 45 days after sowing.",
    "prevention_hi": "शुरुआती 45 दिनों तक खेत को खरपतवार मुक्त रखें।"
  },
  "Tomato___Early_blight": {
    "crop": "Tomato",
    "disease_name_en": "Tomato Early Blight (Alternaria solani)",
    "disease_name_hi": "टमाटर का अगेती झुलसा (अल्टरनेरिया)",
    "is_healthy": false,
    "symptoms_en": "Brown to black lesions with concentric rings (target-like pattern) surrounded by a yellow halo on lower mature leaves, progressing upward.",
    "symptoms_hi": "निचली पुरानी पत्तियों पर संकेंद्री छल्लेदार (टारगेट बोर्ड) काले-भूरे धब्बे जिनके चारों ओर पीला घेरा होता है।",
    "organic_remedy_en": "Foliar spray with Bacillus subtilis @ 5g/L or copper oxychloride formulation with neem oil (3 ml/L).",
    "organic_remedy_hi": "बैसिलस सबटिलिस (5 ग्राम/लीटर) या कॉपर ऑक्सीक्लोराइड व नीम तेल का छिड़काव करें।",
    "chemical_treatment_en": "Chlorothalonil 75% WP @ 2 g/L or Difenoconazole 25% EC @ 0.5 ml/L or Azoxystrobin 18.2% + Difenoconazole 11.4% SC @ 1 ml/L.",
    "chemical_treatment_hi": "क्लोरोथैलोनिल 75% WP (2 ग्राम/लीटर) या डाइफेनोकोनाज़ोल (0.5 मिली/लीटर) का छिड़काव करें।",
    "prevention_en": "Mulch soil around plants; stake tomato vines off the ground; avoid overhead sprinkler watering.",
    "prevention_hi": "मल्चिंग करें, पौधों को सहारा देकर जमीन से ऊपर रखें और ड्रिप सिंचाई का प्रयोग करें।"
  },
  "Tomato___Late_blight": {
    "crop": "Tomato",
    "disease_name_en": "Tomato Late Blight (Phytophthora infestans)",
    "disease_name_hi": "टमाटर का पछेती झुलसा (फाइटोफ्थोरा)",
    "is_healthy": false,
    "symptoms_en": "Large irregular pale green to greasy water-soaked spots rapidly turning dark brown or black on leaves and stems. White downy mold on undersides in humid conditions.",
    "symptoms_hi": "पत्तियों और तनों पर तेजी से फैलने वाले काले-भूरे जलसिक्त धब्बे। अधिक नमी में पत्ती के नीचे सफेद फफूंद दिखती है।",
    "organic_remedy_en": "Bordeaux mixture 1% spray; preventive applications of Trichoderma harzianum or bio-copper.",
    "organic_remedy_hi": "बोर्डो मिश्रण 1% का छिड़काव करें। ट्राइकोडर्मा हरजिएनम का सुरक्षात्मक स्प्रे करें।",
    "chemical_treatment_en": "Metalaxyl 8% + Mancozeb 64% WP (Ridomil Gold @ 2.5 g/L) or Dimethomorph 50% WP @ 1 g/L.",
    "chemical_treatment_hi": "मेटालेक्सिल + मैंकोज़ेब (2.5 ग्राम/लीटर) या डाइमेशोमॉर्फ (1 ग्राम/लीटर) का तुरंत छिड़काव करें।",
    "prevention_en": "Destroy cull piles; maintain wide row spacing for good air circulation; use resistant hybrids.",
    "prevention_hi": "उचित दूरी पर रोपाई करें ताकि हवा का आवागमन बना रहे; रोगग्रस्त पौधों को तुरंत हटा दें।"
  },
  "Tomato___healthy": {
    "crop": "Tomato",
    "disease_name_en": "Healthy Tomato Plant",
    "disease_name_hi": "स्वस्थ टमाटर का पौधा",
    "is_healthy": true,
    "symptoms_en": "Deep green compound leaves, firm turgid leaflets, healthy blossom clusters, free of blight spots, curl, or wilting.",
    "symptoms_hi": "पत्तियां गहरी हरी, मजबूत और किसी भी प्रकार के झुलसा, मरोड़िया या सड़न से पूर्णतः मुक्त हैं।",
    "organic_remedy_en": "Apply vermicompost and foliar spray Panchagavya 3% every 15 days.",
    "organic_remedy_hi": "वर्मीकम्पोस्ट और 3% पंचगव्य का नियमित छिड़काव रखें।",
    "chemical_treatment_en": "No chemical treatment required. Maintain balanced calcium and potassium fertilization to prevent blossom end rot.",
    "chemical_treatment_hi": "किसी रासायनिक दवा की जरूरत नहीं। कैल्शियम व पोटाश की संतुलित मात्रा दें।",
    "prevention_en": "Proper staking, pruning suckers, and uniform drip irrigation.",
    "prevention_hi": "उचित सहारा दें और नियमित ड्रिप सिंचाई बनाए रखें।"
  },
  "Corn___Common_rust": {
    "crop": "Corn",
    "disease_name_en": "Corn Common Rust (Puccinia sorghi)",
    "disease_name_hi": "मक्का का कॉमन रस्ट (रतुआ रोग)",
    "is_healthy": false,
    "symptoms_en": "Golden-brown to cinnamon-brown powdery pustules scattered prominently on both upper and lower leaf surfaces, erupting through leaf epidermis.",
    "symptoms_hi": "पत्तियों की दोनों सतहों पर सुनहरे-भूरे से दालचीनी जैसे रंग के फफोलेदार पाउडर वाले धब्बे बनते हैं।",
    "organic_remedy_en": "Spray fermented sour buttermilk (chhaas) @ 5% with garlic extract; apply bio-fungicide Bacillus amyloliquefaciens.",
    "organic_remedy_hi": "खट्टी छाछ (5%) व लहसुन का अर्क स्प्रे करें। जैव कवकनाशी बैसिलस का प्रयोग करें।",
    "chemical_treatment_en": "Mancozeb 75% WP @ 2.5 g/L or Azoxystrobin 18.2% + Difenoconazole 11.4% SC @ 1 ml/L or Pyraclostrobin 20% WG.",
    "chemical_treatment_hi": "मैंकोज़ेब 75% WP (2.5 ग्राम/लीटर) या एजोक्सीस्ट्रोबिन + डाइफेनोकोनाज़ोल (1 मिली/लीटर) का छिड़काव करें।",
    "prevention_en": "Plant resistant maize hybrids; sow early in the season to escape late rust build-up.",
    "prevention_hi": "रोग प्रतिरोधी संकर बीज लगाएं और समय पर बुवाई करें।"
  },
  "Corn___Leaf_blight": {
    "crop": "Corn",
    "disease_name_en": "Corn Leaf Blight / Northern Corn Leaf Blight (Exserohilum turcicum)",
    "disease_name_hi": "मक्का का पत्ती झुलसा (उत्तरी लीफ ब्लाइट)",
    "is_healthy": false,
    "symptoms_en": "Long elliptical / cigar-shaped grayish-green to tan lesions parallel to leaf veins, expanding up to 15 cm and causing severe blighting of leaves.",
    "symptoms_hi": "पत्तियों पर सिगार के आकार के लंबे भूरे-धूसर धब्बे जो नसों के समानांतर बढ़ते हैं और पत्ती को सुखा देते हैं।",
    "organic_remedy_en": "Foliar spray with Trichoderma viride @ 5g/L or 5% neem seed kernel extract (NSKE).",
    "organic_remedy_hi": "ट्राइकोडर्मा विरिडी (5 ग्राम/लीटर) या 5% नीम के बीज का अर्क छिड़कें।",
    "chemical_treatment_en": "Mancozeb 75% WP @ 2.5 g/L or Propiconazole 25% EC @ 1 ml/L at first appearance of lesions.",
    "chemical_treatment_hi": "मैंकोज़ेब 75% WP (2.5 ग्राम/लीटर) या प्रोपिकोनाज़ोल 25% EC (1 मिली/लीटर) का तुरंत छिड़काव करें।",
    "prevention_en": "Deep plow crop residues after harvest; practice 2-year crop rotation with non-grasses.",
    "prevention_hi": "कटाई के बाद गहरी जुताई करें और गैर-घास कुल की फसलों के साथ चक्र अपनाएं।"
  },
  "Corn___healthy": {
    "crop": "Corn",
    "disease_name_en": "Healthy Corn / Maize Leaf",
    "disease_name_hi": "स्वस्थ मक्का की पत्ती",
    "is_healthy": true,
    "symptoms_en": "Broad, vibrant green arching leaf blades with clean midribs and no rust pustules, blighting, or streaking.",
    "symptoms_hi": "पत्तियां पूरी तरह हरी, चमकदार, चौड़ी और किसी भी रतुआ या झुलसा रोग से मुक्त हैं।",
    "organic_remedy_en": "Apply Jeevamrutha through irrigation; spray zinc sulfate (0.5%) + lime to ensure micronutrient adequacy.",
    "organic_remedy_hi": "जीवामृत दें और जिंक सल्फेट (0.5%) का सुरक्षात्मक छिड़काव करें।",
    "chemical_treatment_en": "No chemical fungicide required. Maintain split nitrogen application (basal, knee-high, and tasseling stages).",
    "chemical_treatment_hi": "किसी रासायनिक दवा की जरूरत नहीं। संतुलित यूरिया तीन चरणों में दें।",
    "prevention_en": "Ensure proper field drainage and balanced NPK + zinc nutrition.",
    "prevention_hi": "खेत में जल निकास अच्छा रखें और जिंक की कमी न होने दें।"
  },
  "Apple___Scab": {
    "crop": "Apple",
    "disease_name_en": "Apple Scab (Venturia inaequalis)",
    "disease_name_hi": "सेब का स्कैब रोग (वेन्चुरिया इनइक्वलिस)",
    "is_healthy": false,
    "symptoms_en": "Olive-green to dull black velvety spots on leaf surfaces and fruit skins, with margins turning irregular and tissues puckering or curling.",
    "symptoms_hi": "पत्तियों और फलों पर जैतूनी-हरे से मखमली काले धब्बे बनते हैं, जिससे पत्तियां मुड़कर विकृत हो जाती हैं।",
    "organic_remedy_en": "Foliar spray with wettable sulfur @ 3g/L or lime-sulfur mixture during green tip stage; spray bio-formulation of Bacillus subtilis.",
    "organic_remedy_hi": "घुलनशील गंधक (3 ग्राम/लीटर) या चूना-गंधक का छिड़काव करें। बैसिलस सबटिलिस का प्रयोग करें।",
    "chemical_treatment_en": "Difenoconazole 25% EC @ 0.3 ml/L or Captan 50% WP @ 2.5 g/L or Dodine 65% WP @ 1 g/L.",
    "chemical_treatment_hi": "डाइफेनोकोनाज़ोल 25% EC (0.3 मिली/लीटर) या कैप्टान (2.5 ग्राम/लीटर) का छिड़काव करें।",
    "prevention_en": "Collect and destroy fallen leaf litter in autumn; prune tree canopy to maximize sunlight and airflow.",
    "prevention_hi": "पतझड़ में गिरी पत्तियां नष्ट करें और पेड़ों की उचित छंटाई करें ताकि धूप व हवा मिल सके।"
  },
  "Apple___healthy": {
    "crop": "Apple",
    "disease_name_en": "Healthy Apple Foliage",
    "disease_name_hi": "स्वस्थ सेब की पत्ती",
    "is_healthy": true,
    "symptoms_en": "Serrated, firm dark green leaves without velvety olive lesions, powdery coating, or rust spots.",
    "symptoms_hi": "पत्तियां पूरी तरह स्वस्थ, गहरे हरे रंग की और किसी भी प्रकार के स्कैब या फफूंद धब्बों से मुक्त हैं।",
    "organic_remedy_en": "Apply well-rotted farmyard manure and seaweed bio-extract as a foliar tonic.",
    "organic_remedy_hi": "सड़ी गोबर खाद और समुद्री शैवाल अर्क का छिड़काव करें।",
    "chemical_treatment_en": "No chemical treatment required. Apply regular horticultural mineral oil in dormant phase.",
    "chemical_treatment_hi": "रोग नहीं है। सुप्त अवस्था में केवल हॉर्टीकल्चरल मिनरल ऑयल का स्प्रे करें।",
    "prevention_en": "Annual winter pruning, tree sanitation, and balanced boron/calcium nutrition.",
    "prevention_hi": "सर्दियों में छंटाई और बोरॉन व कैल्शियम का उचित संतुलन रखें।"
  },
  "Grape___Black_rot": {
    "crop": "Grape",
    "disease_name_en": "Grape Black Rot (Guignardia bidwellii / Phyllosticta ampelicida)",
    "disease_name_hi": "अंगूर का ब्लैक रॉट (काला सड़न रोग)",
    "is_healthy": false,
    "symptoms_en": "Circular reddish-brown necrotic spots with distinct dark brown margins on leaves; tiny black speck-like pycnidia fruiting bodies embedded within lesions. Berries turn into hard black shriveled mummies.",
    "symptoms_hi": "पत्तियों पर लाल-भूरे गोल धब्बे जिनके किनारों पर गहरा भूरा घेरा और अंदर काले बिंदु होते हैं। अंगूर के दाने सूखकर काले पड़ जाते हैं।",
    "organic_remedy_en": "Bordeaux mixture 1% spray; foliar application of copper hydroxide @ 2 g/L or Trichoderma viride.",
    "organic_remedy_hi": "1% बोर्डो मिश्रण या कॉपर हाइड्रॉक्साइड (2 ग्राम/लीटर) का छिड़काव करें।",
    "chemical_treatment_en": "Mancozeb 75% WP @ 2.5 g/L or Myclobutanil 10% WP @ 1 g/L or Azoxystrobin 23% SC @ 1 ml/L.",
    "chemical_treatment_hi": "मैंकोज़ेब 75% WP (2.5 ग्राम/लीटर) या माइक्लोबुटानिल (1 ग्राम/लीटर) का छिड़काव करें।",
    "prevention_en": "Prune out and burn all infected mummified berry clusters and dead canes; improve canopy aeration.",
    "prevention_hi": "सूखे रोगग्रस्त दानों और शाखाओं को काटकर जलाएं; बेलों में हवा का बहाव सुधारें।"
  },
  "Grape___healthy": {
    "crop": "Grape",
    "disease_name_en": "Healthy Grape Leaf",
    "disease_name_hi": "स्वस्थ अंगूर की पत्ती",
    "is_healthy": true,
    "symptoms_en": "Broad, intact palmately veined green grapevine leaves without necrotic brown spots, downy patches, or shriveled margins.",
    "symptoms_hi": "पत्तियां पूरी तरह हरी, चमकदार और किसी भी ब्लैक रॉट, डाउनी मिल्ड्यू या कीट प्रकोप से मुक्त हैं।",
    "organic_remedy_en": "Foliar spray with vermiwash (5%) and apply Trichoderma to root zone.",
    "organic_remedy_hi": "वर्मीवाश का छिड़काव करें और जड़ क्षेत्र में ट्राइकोडर्मा डालें।",
    "chemical_treatment_en": "No chemical treatment required. Maintain micronutrient spray schedule (magnesium and zinc).",
    "chemical_treatment_hi": "किसी रासायनिक दवा की जरूरत नहीं। मैग्नीशियम व जिंक का संतुलित पोषण रखें।",
    "prevention_en": "Canopy management through shoot thinning and trellising to avoid microclimatic humidity.",
    "prevention_hi": "बेलों की छंटाई और सही मचान व्यवस्था रखें ताकि अत्यधिक नमी न बने।"
  }
};

if (typeof window !== 'undefined') {
  window.AGRONOMIC_KNOWLEDGE = AGRONOMIC_KNOWLEDGE;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { AGRONOMIC_KNOWLEDGE };
}
